"""erp sync logs inbound table

Revision ID: cf6c28066eca
Revises: 9fedf51dd716
Create Date: 2026-08-13 20:25:40.511994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.core.db.base_model import BigIntPk, GUID


# revision identifiers, used by Alembic.
revision: str = 'cf6c28066eca'
down_revision: Union[str, None] = '9fedf51dd716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_sync_logs',
    sa.Column('sync_type', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_pulled', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('id', BigIntPk(), autoincrement=True, nullable=False),
    sa.Column('public_id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_erp_sync_logs_deleted_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erp_sync_logs'))
    )
    op.create_index(op.f('ix_erp_sync_logs_is_deleted'), 'erp_sync_logs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_erp_sync_logs_public_id'), 'erp_sync_logs', ['public_id'], unique=True)
    op.create_index('ix_esl_entity_type', 'erp_sync_logs', ['entity_type'], unique=False)
    op.create_index('ix_esl_status', 'erp_sync_logs', ['status'], unique=False)
    op.create_index('ix_esl_sync_type', 'erp_sync_logs', ['sync_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_esl_sync_type', table_name='erp_sync_logs')
    op.drop_index('ix_esl_status', table_name='erp_sync_logs')
    op.drop_index('ix_esl_entity_type', table_name='erp_sync_logs')
    op.drop_index(op.f('ix_erp_sync_logs_public_id'), table_name='erp_sync_logs')
    op.drop_index(op.f('ix_erp_sync_logs_is_deleted'), table_name='erp_sync_logs')
    op.drop_table('erp_sync_logs')
    # ### end Alembic commands ###
