"""
Base ORM model + cross-cutting mixins.

Implements Phase 3 (Database Foundation) standards:
  - Dual ID strategy: internal BIGINT `id` for FKs/joins, public UUID `public_id`
    for anything exposed via API (§6.1).
  - UTC TIMESTAMPTZ `created_at` / `updated_at` on every table (§6.3).
  - Soft delete: `is_deleted` / `deleted_at` / `deleted_by` (§6.4).
  - `SnapshotMixin` for ERP-owned reference data: `erp_id`, `sync_status`,
    `synced_at` (§6.7).

Every table in every module MUST inherit `BaseMixin` (directly, or via
`SnapshotMixin` which itself inherits `BaseMixin`). This is enforced by a CI
reflection test (see tests/unit/test_base_mixin_contract.py, added in Phase 20).
"""
from __future__ import annotations

import uuid
from datetime import datetime, timezone

from sqlalchemy import BigInteger, Boolean, DateTime, ForeignKey, MetaData, String
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, declared_attr, mapped_column


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


# Naming convention enforced at the metadata level so autogenerated Alembic
# constraint names always match Phase 3 §6.2 (ix_/uq_/fk_ prefixes).
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Root declarative base shared by every module's models.py."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class BaseMixin:
    """
    Standard columns every business table gets (Phase 3 §6.1, §6.3, §6.4).

    NOTE: append-only history/log tables are the one documented exception that
    may skip `is_deleted`/`deleted_at`/`deleted_by` (they still keep timestamps
    and the dual-ID strategy) - see Phase 3 §9.
    """

    id: Mapped[int] = mapped_column(
        BigInteger, primary_key=True, autoincrement=True
    )
    public_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        unique=True,
        nullable=False,
        default=uuid.uuid4,
        index=True,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utcnow
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utcnow, onupdate=utcnow
    )
    is_deleted: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, index=True
    )
    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    @declared_attr
    def deleted_by(cls) -> Mapped[int | None]:  # noqa: N805
        return mapped_column(
            BigInteger, ForeignKey("users.id"), nullable=True
        )

    def mark_deleted(self, actor_user_id: int) -> None:
        """Soft-delete helper - services call this instead of raw attribute sets."""
        self.is_deleted = True
        self.deleted_at = utcnow()
        self.deleted_by = actor_user_id


class SnapshotMixin(BaseMixin):
    """
    For tables owned by ERP and mirrored read-only in Exam Engine
    (Board/School/Class/Subject/Chapter/Unit/Topic, Student/Teacher snapshots).
    Phase 3 §6.7.
    """

    erp_id: Mapped[str] = mapped_column(String(64), nullable=False, unique=True, index=True)
    sync_status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="SYNCED"
    )  # SYNCED | STALE | MISSING_IN_ERP
    synced_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utcnow
    )
